## Write a Numpy program to compute the multiplication of two given matrixes

In [ ]:
import numpy as np
B = np.array([[[1,2,3], [4,5,6], [7,8,9]],
              [[10,11,12], [13,14,15], [16,17,18]],
              [[19,20,21], [22,23,24], [25,26,27]]])
C = np.array([[[1,2,3], [4,5,6], [7,8,9]],
              [[10,11,12], [13,14,15], [16,17,18]],
              [[19,20,21], [22,23,24], [25,26,27]]])
D = B + C
X = B * C
print(D)
print(X)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]
[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]


## Write a NumPy program to compute the determinant of a given square array

In [ ]:
import numpy as np
A = np.array([[1,2,3],
             [4,5,6],
              [7,14,9]])
C = np.linalg.det(A)
print(A)
print(C)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 14  9]]
36.0


## Write a NumPy program to compute the cross product of two given vectors

In [2]:
import numpy as np

#initialize arrays
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])

#compute cross product
output1 = np.cross(A, B)
output2 = np.cross(B, A)

print(output1)
print(output2)

[20 -4 -3]
[-20   4   3]


## Write a NumPy program to compute the condition number of a given matrix

In [5]:
matrix = np.array([[4, 2, 0], [3, 1, 2], [1, 6, 4]])
  
print("Original matrix:")
print(matrix)
  
# Output
result =  np.linalg.cond(matrix)
  
print("Condition number of the matrix:")
print(result)

Original matrix:
[[4 2 0]
 [3 1 2]
 [1 6 4]]
Condition number of the matrix:
5.347703616656448


## Write a NumPy program to compute the inverse of a given matrix

In [7]:
arr = np.array([[1, 2, 3], 
                [4, 9, 6], 
                [7, 8, 9]])
print("Original array is ")
print(arr)
inverse_array = np.linalg.inv(arr)
print("Inverse array is ")
print(inverse_array)
print()

Original array is 
[[1 2 3]
 [4 9 6]
 [7 8 9]]
Inverse array is 
[[-0.6875     -0.125       0.3125    ]
 [-0.125       0.25       -0.125     ]
 [ 0.64583333 -0.125      -0.02083333]]

